FROM node:alpine
MAINTAINER toan <toan@ejoy.io>

RUN npm install eslint eslint-config-airbnb eslint-plugin-jsx-a11y eslint-plugin-react eslint-config-airbnb-base eslint-plugin-import -g

VOLUME ["/app"]

WORKDIR /app
